### ISSUE TITLE
how to use dataset

### ISSUE THREAD

**Issue by whitesockcat** [ys-zong/VL-ICL#2]
Good job, your work inspire me a lot.

Here is some little question about dataset.
1. I don't see the train test split from dataset link.
2. I don't know how to orgnize in contex sample from dataset. There seems is only sample one by one, not few shot.

Looking forward to get your responce!

**Comment by whitesockcat** [comment]
> Good job, your work inspire me a lot.
> 
> Here is some little question about dataset.
> 
> 1. I don't see the train test split from dataset link.
> 2. I don't know how to orgnize in contex sample from dataset. There seems is only sample one by one, not few shot.
> 
> Looking forward to get your responce!

I got it, query.json is test split. support.json is train split

**Comment by whitesockcat** [comment]
> Good job, your work inspire me a lot.
> 
> Here is some little question about dataset.
> 
> 1. I don't see the train test split from dataset link.
> 2. I don't know how to orgnize in contex sample from dataset. There seems is only sample one by one, not few shot.
> 
> Looking forward to get your responce!

https://github.com/ys-zong/VL-ICL/blob/main/utils/ICL_utils.py here is data using solution.

Good job!

**Comment by ys-zong** [comment]
Yes, exactly.
