### ISSUE TITLE
can I sft MLLM with your train split?

### ISSUE THREAD

**Issue by whitesockcat** [ys-zong/VL-ICL#5]
can I sft MLLM with your train split?

**Comment by ys-zong** [comment]
In theory yes, it would be useful if you want to compare fine-tuning and ICL. But keep in mind that some train sets like Open MiniImagenet contain random words (e.g. blicket) as labels for the model to in-context learn the mapping. So if you fine-tune with such sets, it may harm the model's general performance.

**Comment by whitesockcat** [comment]
OK thanks



---Original---
From: "Yongshuo ***@***.***&gt;
Date: Sat, May 11, 2024 21:41 PM
To: ***@***.***&gt;;
Cc: "Robin ***@***.******@***.***&gt;;
Subject: Re: [ys-zong/VL-ICL] can I sft MLLM with your train split? (Issue #5)




 
In theory yes, it would be useful if you want to compare fine-tuning and ICL. But keep in mind that some train sets like Open MiniImagenet contain random words (e.g. blicket) as labels for the model to in-context learn the mapping. So if you fine-tune with such sets, it may harm the model's general performance.
